version: '3.8'

services:
  account-service:
    build: ./account-service
    ports:
      - "8081:8080"
    networks:
      - bank-network

  customer-service:
    build: ./customer-service
    ports:
      - "8082:8080"
    networks:
      - bank-network

  user-service:
    build: ./user-service
    ports:
      - "8083:8080"
    networks:
      - bank-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - account-service
      - customer-service
      - user-service
    networks:
      - bank-network

  frontend-service:
    build: ./frontend-service
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge
