version: '3.8'

services:
  account-service:
    build: ./account-service
    ports:
      - "8081:8080"
    networks:
      - bank-network

  customer-service:
    build: ./customer-service
    ports:
      - "8082:8080"
    networks:
      - bank-network

  user-service:
    build: ./user-service
    ports:
      - "8083:8080"
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge
