name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Build and push each Dockerfile
      - name: Build and push account-service
        run: |
          docker build ./account-service -f ./account-service/Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/account-service:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/account-service:latest

      - name: Build and push customer-service
        run: |
          docker build ./customer-service -f ./customer-service/Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/customer-service:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/customer-service:latest

      - name: Build and push user-service
        run: |
          docker build ./user-service -f ./user-service/Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/user-service:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/user-service:latest

      - name: Build and push api-gateway
        run: |
          docker build ./api-gateway -f ./api-gateway/Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/api-gateway:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/api-gateway:latest

      - name: Build and push frontend-service
        run: |
          docker build ./frontend-service -f ./frontend-service/Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/frontend-service:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/frontend-service:latest
